"""add payload_id as hashing

Revision ID: 870e07c40a33
Revises: b197905c22f8
Create Date: 2025-09-20 18:39:02.726245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870e07c40a33'
down_revision: Union[str, None] = 'b197905c22f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cache_payloads', sa.Column('payload_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_cache_payloads_payload_id'), 'cache_payloads', ['payload_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cache_payloads_payload_id'), table_name='cache_payloads')
    op.drop_column('cache_payloads', 'payload_id')
    # ### end Alembic commands ###
